### PR TITLE
feat: [BREAKING_CHANGE] support class based async controllers.

### PR DESCRIPTION
**Pull request by zhang-z**
Closes https://github.com/eggjs/egg/issues/894 and https://github.com/eggjs/egg/issues/1382.
BREAKING CHANGE:
  Use a single async function as module's default export won't be supported.

### CODE REVIEW

**Comment by ngot** [comment]
我发个 Major 吧。

**Comment by ngot** [comment]
『Use a single async function as module's default export won't be supported.』

Maybe, it means generator function is no longer supported?

**Comment by zhang-z** [comment]
@ngot , 更详细的解释详见egg issue: https://github.com/eggjs/egg/issues/894#issuecomment-338677645
generator function还是可以用的，这点没有breaking compatibility。`exports.XXX = async function`这种写法也可以。`module.exports = async function` 这种不行

**Comment by ngot** [comment]
可以的。我发个major就行了。

**Comment by ngot** [comment]
+ egg-socket.io@3.0.0

**Pull request merged**
