### PR TITLE
feat: Allow users to re-define new generatorID for Socket Server

### PR DESCRIPTION
**Pull request by Maledong**
Ref: 
1) https://github.com/eggjs/egg/issues/2850,
2) https://github.com/eggjs/egg/issues/2878,
3) https://github.com/eggjs/egg-socket.io/pull/42

Considering there're more than one requiring for this feature, we
think we can add this by exposing this interface.

PS：Remove the version check in the unit test, because we don't need this (Our node MUST BE >= 8.x).

### CODE REVIEW

**Comment by ngot** [comment]
Thanks for your contribution. 👍 

The whole PR looks good. 
One more thing, it is better to add documentation to illustrate the usage and don't forget this includes both English and Chines documentation.

Thanks for your time.

**Comment by Maledong** [comment]
@ngot：OK, I'll submit it soon

**Comment by Maledong** [comment]
@ngot：Maybe Node should support 10.x instead of 9.x :)

**Comment by ngot** [comment]
@Maledong Feel free to make the change.

**Comment by Maledong** [comment]
@ngot：Thanks! I just feel worried if I should put so many unrelated things together in this push.
Now I'll update them and have a try.

**Comment by Maledong** [comment]
Now I submitted them on purpose for you to see clearly. So if OK, you can choose `squach and merge`.
Hope you understand.

**Comment by Maledong** [comment]
@ngot：I'm not sure why it doesn't support Nodejs >= 10.x. And uws is totally deprecated. So I have to find another solution. But this can be merged if it can pass 8.x and 9.x.

**Pull request merged**
